[build-system]
requires = ["setuptools>=45"]
build-backend = "setuptools.build_meta"

[project]
name = "shared"
version = "0.1.0"

[tool.setuptools]
packages = ["shared"]

[tool.setuptools.package-dir]
shared = "."